174945853 — rm AASM gem, update Publishable module
concord-consortium/rigse pull request #854
Opened 2020-09-23 20:41 UTC by knowuh

[#174945853]
https://www.pivotaltracker.com/story/show/174945853

2020-09-24 10:49 UTC, dougmartin approved these changes
Looks good - just had a couple of questions.

2020-09-24 10:49 UTC, dougmartin commented on commit_notes.txt
> +
@knowuh did you mean to leave this file in the PR?

2020-09-24 10:49 UTC, dougmartin commented on rails/spec/libs/publishable_spec.rb
> +class DummyClass
Do you still need this `aasm_column` column in the test class?

2020-09-24 11:19 UTC, dougmartin requested changes
Need to implement `publish` method.

2020-09-24 11:19 UTC, dougmartin commented on rails/lib/publishable.rb
> +      def publish!
I just looked at the test results and it looks like you also need to add a `publish` method:

```
undefined method `publish' for #<ExternalActivity:0x0000000006223a48>
Did you mean?  publish!
               published?
               public?
/home/travis/.rvm/gems/ruby-2.3.7/gems/activemodel-4.0.13/lib/active_model/attribute_methods.rb:439:in `method_missing'
/home/travis/.rvm/gems/ruby-2.3.7/gems/activerecord-4.0.13/lib/active_record/attribute_methods.rb:168:in `method_missing'
/home/travis/build/[secure]-consortium/rigse/rails/lib/mock_data/create_default_data.rb:661:in `block in create_default_study_materials'
```

2020-09-24 13:47 UTC, knowuh commented
@dougmartin thanks for the review,  I will clean those items up.

2020-09-24 21:14 UTC, knowuh commented
@dougmartin  I think we are ready with this one.

2020-09-28 12:30 UTC, dougmartin approved these changes

2020-09-28 12:31 UTC, merged