Added class offering link click logging [#174653677]
concord-consortium/rigse pull request #925
Opened 2021-01-19 12:05 UTC by dougmartin

This adds a generic logger client to the portal with the offering details component as the first user of the client.

The following events are logged:

- clickedPreviewLink
- clickedTeacherEditionLink
- clickedReportLink
- clickedExternalReport

in each case the event_value is the url of the link.

2021-01-19 12:08 UTC, dougmartin commented
@scytacki A couple of notes:

1. This defines a new application name ('rigse-log') for the portal log messages
2. I wasn't sure if we wanted to use snake_case or camelCase for the event names so I went with cameCase.

2021-01-25 21:45 UTC, scytacki requested changes
looks good, just one oversight in external report handling I think.

2021-01-25 21:45 UTC, scytacki commented on react-components/src/library/components/assigments/offering-details.js
> +            }
This seems to be missing the activity, and parameters that other events have.

The activity of these report launches is going to have to change at some point, but that can be done in a later PR and using `activity: [id]` seems good enough for now.

2021-01-26 12:38 UTC, dougmartin commented
@scytacki I added a follow on commit to add the activity and parameters to the other event logged: https://github.com/concord-consortium/rigse/pull/925/commits/9b28ece75471d5708f68d4e0cddbf630adaf3486

2021-01-26 15:40 UTC, scytacki approved these changes
looks good to me

2021-01-26 15:40 UTC, merged